AllCops:
  DisplayCopNames: true
  Exclude:
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
