AllCops:
  DisplayCopNames: true
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
