default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development:
  <<: *default
  database: sklife_development

test:
  <<: *default
  database: sklife_test

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(:db, :user) %>
  password: <%= Rails.application.credentials.dig(:db, :pass) %>
  database: <%= Rails.application.credentials.dig(:db, :base) %>
