default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: sklife_development
  primary_replica:
    <<: *default
    database: sklife_development
    replica: true

test:
  <<: *default
  database: sklife_test

default_production: &default_production
  username: sklife
  password: <%= ENV['SKLIFE_DATABASE_PASSWORD'] %>

production:
  primary:
    <<: *default
    <<: *default_production
    database: sklife_production
  primary_replica:
    <<: *default
    <<: *default_production
    database: sklife_production
    replica: true
